/**
 * @file templates.ts
 * @description Auto-reply template CRUD operations backed by Prisma (SQLite).
 *
 * ARCHITECTURE / INTEGRATION:
 *   - Templates are persisted in the AutoReplyTemplate Prisma model.
 *   - matcher.ts uses these templates to match incoming messages.
 *   - message-pipeline checks for auto-reply matches before LLM generation.
 *
 * DATA MAPPING:
 *   The Prisma model stores `channels` as a Json column (serialized string[]).
 *   All read paths deserialize it back to string[] via parseChannels().
 */

import { createLogger } from "../logger.js"
import { prisma } from "../database/index.js"

const log = createLogger("auto-reply.templates")

/** Represents a single auto-reply template that maps a trigger to a canned response. */
export interface AutoReplyTemplate {
  /** Unique identifier for the template. */
  id: string
  /** Owner user ID. */
  userId: string
  /** Human-readable name for the template. */
  name: string
  /** Keyword, regex pattern, or exact string to match against. */
  trigger: string
  /** How the trigger should be evaluated. */
  triggerType: "keyword" | "regex" | "exact"
  /** The response text to send when the trigger matches. */
  response: string
  /** Channel IDs this template applies to. Empty array means all channels. */
  channels: string[]
  /** Whether the template is active. */
  enabled: boolean
  /** Timestamp when the template was created. */
  createdAt: Date
}

/**
 * Parses the JSON channels column from Prisma into a typed string[].
 * @param raw - Raw value from a prisma row's channels field.
 * @returns Parsed string array, or empty array on parse failure.
 */
function parseChannels(raw: unknown): string[] {
  if (Array.isArray(raw)) {
    return raw.filter((c): c is string => typeof c === "string")
  }
  if (typeof raw === "string") {
    try {
      const parsed: unknown = JSON.parse(raw)
      if (Array.isArray(parsed)) {
        return parsed.filter((c): c is string => typeof c === "string")
      }
    } catch {
      // fall through to empty array
    }
  }
  return []
}

/**
 * Maps a raw Prisma AutoReplyTemplate row to the typed AutoReplyTemplate interface.
 * @param row - Raw row returned by prisma.autoReplyTemplate queries.
 * @returns Typed AutoReplyTemplate with channels deserialized as string[].
 */
function mapRow(row: {
  id: string
  userId: string
  name: string
  trigger: string
  triggerType: string
  response: string
  channels: unknown
  enabled: boolean
  createdAt: Date
}): AutoReplyTemplate {
  return {
    id: row.id,
    userId: row.userId,
    name: row.name,
    trigger: row.trigger,
    triggerType: row.triggerType as AutoReplyTemplate["triggerType"],
    response: row.response,
    channels: parseChannels(row.channels),
    enabled: row.enabled,
    createdAt: row.createdAt,
  }
}

/**
 * Prisma-backed CRUD store for auto-reply templates.
 *
 * All methods are async because they perform database I/O.
 * Errors are caught, logged, and surfaced as null / false / empty-array returns
 * so callers can degrade gracefully without crashing the pipeline.
 */
export class AutoReplyTemplateStore {
  /**
   * Creates a new auto-reply template and persists it to the database.
   * @param template - Template data without id and createdAt (auto-generated by Prisma).
   * @returns The newly created template, or null if the database write failed.
   */
  async create(
    template: Omit<AutoReplyTemplate, "id" | "createdAt">,
  ): Promise<AutoReplyTemplate | null> {
    try {
      const row = await prisma.autoReplyTemplate.create({
        data: {
          userId: template.userId,
          name: template.name,
          trigger: template.trigger,
          triggerType: template.triggerType,
          response: template.response,
          channels: template.channels,
          enabled: template.enabled,
        },
      })
      log.info("template created", { id: row.id, userId: template.userId, name: template.name })
      return mapRow(row)
    } catch (err: unknown) {
      log.error("create failed", { userId: template.userId, name: template.name, err })
      return null
    }
  }

  /**
   * Retrieves a single template by ID.
   * @param id - Template identifier.
   * @returns The template if found, otherwise null.
   */
  async get(id: string): Promise<AutoReplyTemplate | null> {
    try {
      const row = await prisma.autoReplyTemplate.findUnique({ where: { id } })
      if (!row) return null
      return mapRow(row)
    } catch (err: unknown) {
      log.error("get failed", { id, err })
      return null
    }
  }

  /**
   * Lists all templates belonging to a user, ordered by creation date descending.
   * @param userId - Owner user ID.
   * @returns Array of templates for the user.
   */
  async list(userId: string): Promise<AutoReplyTemplate[]> {
    try {
      const rows = await prisma.autoReplyTemplate.findMany({
        where: { userId },
        orderBy: { createdAt: "desc" },
      })
      return rows.map(mapRow)
    } catch (err: unknown) {
      log.error("list failed", { userId, err })
      return []
    }
  }

  /**
   * Updates mutable fields of an existing template.
   * @param id - Template identifier.
   * @param updates - Partial set of updatable fields.
   * @returns The updated template, or null if not found or write failed.
   */
  async update(
    id: string,
    updates: Partial<
      Pick<AutoReplyTemplate, "name" | "trigger" | "triggerType" | "response" | "channels" | "enabled">
    >,
  ): Promise<AutoReplyTemplate | null> {
    try {
      const row = await prisma.autoReplyTemplate.update({
        where: { id },
        data: {
          ...(updates.name !== undefined ? { name: updates.name } : {}),
          ...(updates.trigger !== undefined ? { trigger: updates.trigger } : {}),
          ...(updates.triggerType !== undefined ? { triggerType: updates.triggerType } : {}),
          ...(updates.response !== undefined ? { response: updates.response } : {}),
          ...(updates.channels !== undefined ? { channels: updates.channels } : {}),
          ...(updates.enabled !== undefined ? { enabled: updates.enabled } : {}),
        },
      })
      log.info("template updated", { id, fields: Object.keys(updates) })
      return mapRow(row)
    } catch (err: unknown) {
      log.warn("update failed — template not found or write error", { id, err })
      return null
    }
  }

  /**
   * Deletes a template by ID.
   * @param id - Template identifier.
   * @returns True if removed, false if not found or delete failed.
   */
  async delete(id: string): Promise<boolean> {
    try {
      await prisma.autoReplyTemplate.delete({ where: { id } })
      log.info("template deleted", { id })
      return true
    } catch (err: unknown) {
      log.warn("delete failed — template not found or write error", { id, err })
      return false
    }
  }

  /**
   * Lists only enabled templates for a user, queried directly from the database.
   * @param userId - Owner user ID.
   * @returns Array of enabled templates for the user.
   */
  async listEnabled(userId: string): Promise<AutoReplyTemplate[]> {
    try {
      const rows = await prisma.autoReplyTemplate.findMany({
        where: { userId, enabled: true },
        orderBy: { createdAt: "desc" },
      })
      return rows.map(mapRow)
    } catch (err: unknown) {
      log.error("listEnabled failed", { userId, err })
      return []
    }
  }
}

/** Singleton template store instance. */
export const templateStore = new AutoReplyTemplateStore()
